<h3>Exercise<h3>

In exercise folder (same level as this notebook on github) there is **hiring.csv**. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,


**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**

<h3>Answer<h3>

53713.86 and 93747.79

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from sklearn import linear_model

In [3]:
df=pd.read_csv('hiring.csv')

In [4]:
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [10]:
print(df.columns)

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [8]:
X=df[["experience","test_score(out of 10)","interview_score(out of 10)"]]

In [9]:
y=df["salary($)"]

## Now its time for data cleaning

In [13]:
df["test_score(out of 10)"].median()

np.float64(8.0)

In [20]:
mean_value=df["test_score(out of 10)"].mean()
print(mean_value)

7.857142857142857

In [21]:

import math
mean_value=math.floor(mean_value)
print(mean_value)

7

In [22]:
df["test_score(out of 10)"].mode()[0]

np.float64(7.0)

In [23]:
df["test_score(out of 10)"]=df["test_score(out of 10)"].fillna(mean_value)

In [24]:
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

## for experience its little tricky,we need module word2number

In [28]:
from word2number import w2n
print(w2n.word_to_num('two point three'))

2.3

In [31]:
df2=df.dropna()

In [32]:
df2

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [33]:
for value in df2["experience"]:
    value=w2n.word_to_num(value)

In [34]:
df2

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

## value ac†s as temporary variable so it wont work

In [35]:
df2["experience"]=df2["experience"].apply(w2n.word_to_num)

/var/folders/n8/qbmv6g7j6vd0tjr7352tnwsw0000gn/T/ipykernel_22013/319188952.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["experience"]=df2["experience"].apply(w2n.word_to_num)

In [36]:
df2

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [38]:
X=df2[["experience","test_score(out of 10)","interview_score(out of 10)"]]
y=df2["salary($)"]

In [39]:
reg=linear_model.LinearRegression()

In [40]:
reg.fit(X,y)

LinearRegression()

**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**

In [44]:
x1=[[2,9,6]]
x2=[[12,10,10]]

In [45]:
predictedValue1=reg.predict(x1)
print(predictedValue1)
predictedValue2=reg.predict(x2)
print(predictedValue2)

[56693.20319849]
[90481.18532455]

/Users/kristalshrestha/Code/LLM_Scratch/venv/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/kristalshrestha/Code/LLM_Scratch/venv/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(