<h2>Categorical Variables and One Hot Encoding</h2>

<img src="Screenshot 2025-08-09 at 7.34.47 PM.png">
<img src="Screenshot 2025-08-09 at 7.35.04 PM.png">
<img src="Screenshot 2025-08-09 at 7.35.11 PM.png">
<img src="Screenshot 2025-08-09 at 7.35.11 PM.png">
<img src="Screenshot 2025-08-09 at 7.35.32 PM.png">
<img src="Screenshot 2025-08-09 at 7.35.40 PM.png">

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('homeprices.csv')

In [3]:
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [5]:
dummies=pd.get_dummies(df["town"])
dummies

    monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [7]:
merged=pd.concat([df,dummies],axis="columns")
merged

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windsor  2600  585000            False        False          True
6      west windsor  2800  615000            False        False          True
7      west windsor  3300  650000            False        False          True
8      west windsor  3600  710000            False        False          True
9       robinsville  2600  575000            False         True         False
10      robinsville  2900  600000            False         True         False
11      robinsville  3100  620000            False         True         False
12      robinsville  3600  695000            False         True         False

In [8]:
final=merged.drop(['town',"west windsor"],axis="columns")
final

    area   price  monroe township  robinsville
0   2600  550000             True        False
1   3000  565000             True        False
2   3200  610000             True        False
3   3600  680000             True        False
4   4000  725000             True        False
5   2600  585000            False        False
6   2800  615000            False        False
7   3300  650000            False        False
8   3600  710000            False        False
9   2600  575000            False         True
10  2900  600000            False         True
11  3100  620000            False         True
12  3600  695000            False         True

In [9]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [12]:
X=final[["area","monroe township","robinsville"]]
X

    area  monroe township  robinsville
0   2600             True        False
1   3000             True        False
2   3200             True        False
3   3600             True        False
4   4000             True        False
5   2600            False        False
6   2800            False        False
7   3300            False        False
8   3600            False        False
9   2600            False         True
10  2900            False         True
11  3100            False         True
12  3600            False         True

# or u can like this efficient method,instead of writing all inputs and assign to X, we can drop the output and assignt to X

In [13]:
X=final.drop("price",axis="columns")
X

    area  monroe township  robinsville
0   2600             True        False
1   3000             True        False
2   3200             True        False
3   3600             True        False
4   4000             True        False
5   2600            False        False
6   2800            False        False
7   3300            False        False
8   3600            False        False
9   2600            False         True
10  2900            False         True
11  3100            False         True
12  3600            False         True

In [14]:
y=final["price"]
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [15]:
model.fit(X,y)

LinearRegression()

In [16]:
predictedValue1=[[2800,0,1]]

In [17]:
model.predict(predictedValue1)

/Users/kristalshrestha/Code/LLM_Scratch/venv/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([590775.63964739])

In [18]:
predictedValue2=[[3400,0,1]]

In [20]:
model.predict(predictedValue2)

/Users/kristalshrestha/Code/LLM_Scratch/venv/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([666914.10449365])

# To check the accuracy of the model

In [21]:
model.score(X,y)

0.9573929037221873

<h2 style='color:purple'>Using pandas to create dummy variables</h2>

<h3 style='color:purple'>Dummy Variable Trap</h3>

When you can derive one variable from other variables, they are known to be multi-colinear. Here
if you know values of california and georgia then you can easily infer value of new jersey state, i.e. 
california=0 and georgia=0. There for these state variables are called to be multi-colinear. In this
situation linear regression won't work as expected. Hence you need to drop one column.

**NOTE: sklearn library takes care of dummy variable trap hence even if you don't drop one of the 
    state columns it is going to work, however we should make a habit of taking care of dummy variable
    trap ourselves just in case library that you are using is not handling this for you**

<h2 style='color:purple'>Using sklearn OneHotEncoder</h2>

First step is to use label encoder to convert town names into numbers

Now use one hot encoder to create dummy variables for each of the town

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
le=LabelEncoder()

In [24]:
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [25]:
dfle=df

In [26]:
dfle

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [30]:
le.fit_transform(dfle["town"])

array([0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 1])

In [29]:
dfle["town"]=le.fit_transform(dfle["town"])
dfle

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [32]:
X=df[["town","area"]]
X

    town  area
0      0  2600
1      0  3000
2      0  3200
3      0  3600
4      0  4000
5      2  2600
6      2  2800
7      2  3300
8      2  3600
9      1  2600
10     1  2900
11     1  3100
12     1  3600

# Convert to 2D numpy array

In [38]:
X=dfle[["town","area"]].values
print(type(X))
print(X)

<class 'numpy.ndarray'>
[[   0 2600]
 [   0 3000]
 [   0 3200]
 [   0 3600]
 [   0 4000]
 [   2 2600]
 [   2 2800]
 [   2 3300]
 [   2 3600]
 [   1 2600]
 [   1 2900]
 [   1 3100]
 [   1 3600]]

In [34]:
y=df["price"]
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [39]:
from sklearn.preprocessing import OneHotEncoder

In [40]:
ohe=OneHotEncoder()

In [41]:
ohe=OneHotEncoder(categorical_features=[0])

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'categorical_features'

Ah! The error is happening because in **recent versions of `scikit-learn`**, the `OneHotEncoder` no longer accepts the `categorical_features` parameter. That parameter was **deprecated in version 0.20** and removed in later versions.

Now, the recommended way is to use the **`ColumnTransformer`** or just pass the data directly if you want to encode all categorical columns.

Here’s how you can fix it:

### 1. Using `ColumnTransformer` (preferred)

```python
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Suppose you want to encode column 0
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])],
    remainder='passthrough'  # keep other columns as they are
)

X = ct.fit_transform(X)
```

### 2. If you want to encode the **entire array**

```python
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
X_encoded = ohe.fit_transform(X[:, 0].reshape(-1, 1)).toarray()
```

✅ Key points:

* `categorical_features` is **no longer valid**.
* Use `ColumnTransformer` to select which columns to encode.
* `.fit_transform()` returns a sparse matrix by default; use `.toarray()` if you need a dense array.

If you want, I can also rewrite your **exact code** using the new `OneHotEncoder` syntax so it works without errors. Do you want me to do that?

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer(
    transformers=[('encoder',OneHotEncoder(),[0])], #encode column 0
    remainder="passthrough" #leave other column as they are
)
X=ct.fit_transform(X)

<h2 style='color:green'>Exercise</h2>

At the same level as this notebook on github, there is an Exercise folder that contains carprices.csv.
This file has car sell prices for 3 different models. First plot data points on a scatter plot chart
to see if linear regression model can be applied. If yes, then build a model that can answer
following questions,

**1) Predict price of a mercedez benz that is 4 yr old with mileage 45000**

**2) Predict price of a BMW X5 that is 7 yr old with mileage 86000**

**3) Tell me the score (accuracy) of your model. (Hint: use LinearRegression().score())**