### Stop words tutorial

In [1]:
import spacy

from spacy.lang.en.stop_words import STOP_WORDS
print(STOP_WORDS)

{'least', 'and', 'just', 'some', 'whenever', 'out', 'otherwise', 'six', 'about', 'whole', 'others', "'ve", 'her', 'this', 'because', 'name', 'serious', 'the', 'last', 'nine', 'without', 'thereby', 'few', 'regarding', 'keep', 'thru', 'still', 'nevertheless', 'your', 'get', 'sometime', 'became', 'against', 'amongst', 'themselves', 'also', 'sixty', 'twelve', 'now', 'five', 'quite', 'towards', 'off', 'due', 'further', 'whence', 'n‘t', 'does', 'using', 'via', 'sometimes', 'whereas', 'may', 'wherein', 'seeming', 'part', 'each', 'these', 'noone', 'while', 'less', 'behind', 'hence', 'yours', 'afterwards', 'during', 'along', 'being', 'side', 'who', '‘ve', 'cannot', 'for', 'other', 'fifteen', 'four', 'their', 'amount', 'too', 'are', 'whereby', 'an', 'third', 'to', 'which', 'twenty', 'myself', 'really', 'very', 'since', '’ve', 'across', 'will', 'ever', 'in', 'whose', 'of', 'under', 'anyone', 'before', 'his', 'how', 'n’t', 'not', 'than', 'by', 'him', 'could', "'re", 'those', 'former', 'mine', 'per', 'done', 'bottom', 'much', 'go', 'i', 'whoever', 'formerly', 'several', 'anyhow', 'at', 'itself', 'please', 'indeed', 'used', 'back', 'among', 'there', 'else', 'fifty', 'with', 'where', 'nor', '’ll', "'m", 'must', 'thereafter', 'either', 'am', 'we', 'ours', 'see', 'everywhere', 'whatever', 'empty', '‘re', 'make', 'do', 'all', 'until', 'except', 'then', 'together', 'eleven', 're', 'latterly', 'whereafter', 'anywhere', 'often', 'take', 'hers', 'every', 'namely', 'yet', 'first', 'from', 'both', 'after', 'put', '‘d', 'above', 'between', 'move', 'when', 'on', 'almost', 'whether', 'more', 'throughout', 'hereafter', 'always', 'say', 'somehow', 'ten', 'anything', 'toward', 'whom', 'meanwhile', 'but', 'perhaps', 'around', 'onto', 'within', 'has', 'upon', 'various', 'becomes', 'seems', 'she', 'down', 'ourselves', 'hundred', 'therein', 'can', 'have', 'through', 'my', 'any', 'many', 'me', 'into', 'made', 'doing', 'something', 'nothing', 'herein', 'another', 'someone', 'had', 'yourself', 'been', "'ll", 'somewhere', "'d", '‘s', 'they', 'beside', 'beforehand', 'over', 'is', 'were', 'three', 'already', 'why', 'up', "n't", 'own', 'everyone', 'besides', 'call', 'whereupon', 'only', 'though', 'again', 'alone', 'them', 'rather', 'might', 'thence', 'would', 'seem', '‘m', 'yourselves', '’m', 'latter', 'seemed', 'anyway', 'everything', '‘ll', 'neither', 'nobody', 'most', 'well', 'as', 'hereby', 'such', 'top', 'be', 'beyond', 'whither', 'moreover', 'should', 'never', 'hereupon', 'us', 'however', 'thus', 'becoming', 'here', 'what', 'enough', 'two', 'was', '’s', 'ca', 'none', 'although', 'even', 'forty', 'mostly', 'himself', 'you', 'so', 'it', 'nowhere', 'unless', 'give', 'thereupon', 'or', 'next', 'a', 'our', "'s", 'if', 'full', 'herself', 'no', 'one', 'show', 'its', 'same', 'that', 'wherever', 'elsewhere', 'front', '’d', 'once', 'eight', 'become', 'therefore', '’re', 'he', 'below', 'did'}

In [2]:
len(STOP_WORDS)

326

In [3]:
nlp = spacy.load("en_core_web_sm")

doc = nlp("We just opened our wings, the flying part is coming soon")
for token in doc:
    if token.is_stop:
        print(token)

We
just
our
the
part
is

In [ ]:
def preprocess(text):
    doc=nlp(text)
    no_stop_words=[]
    for token in doc:
        if not token.is_stop and not token.is_punct:
            no_stop_words.append(token.text)
    return no_stop_words

In [5]:
preprocess("Musk wants time to prepare for a trial over his")

['Musk', 'wants', 'time', 'prepare', 'trial']

In [6]:
preprocess("The other is not other but your divine brother")

['divine', 'brother']

##### Remove stop words from pandas dataframe text column

Dataset is downloaded from: https://www.kaggle.com/datasets/jbencina/department-of-justice-20092018-press-releases
It contains press releases of different court cases from depart of justice (DOJ). The releases contain information such as outcomes of criminal cases, notable actions taken against felons, or other updates about the current administration.

In [9]:
import pandas as pd
df=pd.read_json("doj_press.json",lines=True)
df.shape

(13087, 6)

In [10]:
df.head(5)

,id,title,contents,date,topics,components
0,None,Convicted Bomb Plotter Sentenced to 30 Years,"PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...",2014-10-01T00:00:00-04:00,[],[National Security Division (NSD)]
1,12-919,$1 Million in Restitution Payments Announced t...,WASHINGTON – North Carolina’s Waccamaw River...,2012-07-25T00:00:00-04:00,[],[Environment and Natural Resources Division]
2,11-1002,$1 Million Settlement Reached for Natural Reso...,BOSTON– A $1-million settlement has been...,2011-08-03T00:00:00-04:00,[],[Environment and Natural Resources Division]
3,10-015,10 Las Vegas Men Indicted \r\nfor Falsifying V...,WASHINGTON—A federal grand jury in Las Vegas...,2010-01-08T00:00:00-05:00,[],[Environment and Natural Resources Division]
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]

In [ ]:
df["topics"][0]

[]

In [12]:
type(df["topics"][0])

list

In [13]:
df.describe()

,id,title,contents,date,topics,components
count,12810,13087,13087,13087,13087,13087
unique,12672,12887,13080,2400,253,810
top,13-526,Northern California Real Estate Investor Agree...,"WASHINGTON – ING Bank N.V., a financial inst...",2018-04-13T00:00:00-04:00,[],[Criminal Division]
freq,3,8,2,20,8399,2680

Filter out those rows that do not have any topics associated with the case

In [19]:
def checklength(x):
    if len(x) > 0:
        return True
    else:
        return False
df=df[df["topics"].apply(checklength)]
df.head()

,id,title,contents,date,topics,components
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division]
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U..."
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division]
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]"

In [20]:
df.shape

(4688, 6)

In [21]:
df =df.head(100)
df.shape

(100, 6)

In [22]:
df["contents"]

4      The U.S. Department of Justice, the U.S. Envir...
7      A 131-count criminal indictment was unsealed t...
19     The United States Attorney’s Office for the Mi...
22     21st Century Oncology LLC, has agreed to pay $...
23     21st Century Oncology Inc. and certain of its ...
                             ...
316    Doctor Hid Millions in Secret Accounts in Pana...
318    Defendant Concealed Bank Accounts in Panama an...
321    An Alaskan couple was charged in federal court...
322    A husband and wife pleaded guilty yesterday to...
324    A resident of Big Lake, Alaska was indicted on...
Name: contents, Length: 100, dtype: object

In [24]:
df["contents"].iloc[3]

'21st Century Oncology LLC, has agreed to pay $19.75 million to the government to resolve allegations that it violated the False Claims Act by billing federal health care programs for laboratory tests that were not medically necessary, the Justice Department announced today.\xa0 21st Century is a nationwide provider of integrated cancer care services that is headquartered in Fort Myers, Florida.\xa0 “Today’s settlement demonstrates our unwavering commitment to protect the Medicare trust fund against unscrupulous providers,” said Principal Deputy Assistant Attorney General Benjamin C. Mizer, head of the Justice Department’s Civil Division.\xa0 “Providers who waste taxpayer dollars by billing for unnecessary services will face serious consequences.” The settlement announced today resolves allegations that 21st Century submitted claims to Medicare and Tricare for fluorescence in situ hybridization, or “FISH,” tests that were not medically necessary.\xa0 FISH tests are laboratory tests performed on urine that can detect genetic abnormalities associated with bladder cancer.\xa0 The government alleged that 21st Century submitted claims for unnecessary FISH tests that were ordered by four of its urologists, Dr. Meir Daller, Dr. Steven Paletsky, Dr. David Spellberg and Dr. Robert Scappa, all of whom practiced in the Fort Myers area.\xa0 The government also alleged that 21st Century encouraged these physicians to order unnecessary FISH tests by offering bonuses that were based in part on the number of tests referred to 21st Century’s laboratory.\xa0 Today’s settlement resolves the civil liability of 21st Century only.\xa0 “Charging the government for clearly unnecessary medical services squanders taxpayer dollars,” said U.S. Attorney A. Lee Bentley, III of the Middle District of Florida.\xa0 “Our office will continue to pursue health care providers who defraud the United States, thereby threatening the viability of government health care programs, such as Medicare.” “These tests were ordered to increase profits, not improve the healthcare of patients,” said Special Agent in Charge Shimon Richmond of the Department of Health and Human Services Office of Inspector General (HHS-OIG). “This kind of unvarnished fraud is an attack on Medicare by unscrupulous providers and the OIG and its federal partners will take whatever steps are necessary to stop them.” “This settlement demonstrates the commitment of the Defense Criminal Investigative Service (DCIS) and its law enforcement partners to protect the integrity of the U.S. military health care program (TRICARE) against fraudulent claims for medical services, said Special Agent in Charge John F. Khin of DCIS’s Southeast Field Office.” The settlement resolves allegations originally brought in a lawsuit filed by a whistleblower under the qui tam provisions of the False Claims Act, which allow private parties to bring suit on behalf of the government and to share in any recovery.\xa0 The whistleblower, a former 21st Century Oncology LLC medical assistant, will receive $3.2 million as her share of the recovery in this case. The investigation was handled by the Civil Division’s Commercial Litigation Branch and the Fort Myers Division of the U.S. Attorney’s Office of the Middle District of Florida with assistance from HHS-OIG, DCIS and the FBI.\xa0 This settlement illustrates the government’s emphasis on combating health care fraud and marks another achievement for the Health Care Fraud Prevention and Enforcement Action Team (HEAT) initiative, which was announced in May 2009 by the Attorney General and the Secretary of Health and Human Services.\xa0 The partnership between the two departments has focused efforts to reduce and prevent Medicare and Medicaid financial fraud through enhanced cooperation.\xa0 One of the most powerful tools in this effort is the False Claims Act.\xa0 Since January 2009, the Justice Department has recovered a total of more than $26.7 billion through False Claims Act cases, with more than $16.8 billion of that amount recovered in cases involving fraud against federal health care programs.\xa0\xa0 The lawsuit is captioned United States, State of Florida, ex rel. Mariela Barnes v. Dr. David Spellberg, 21st Century Oncology and Naples Urology Associates, Civil Action No. 2:13-cv-228-FtM-38DNF (M.D. Fla.).\xa0 The claims resolved by the settlement are allegations only, and there has been no determination of liability.\xa0'

In [26]:
type(df["contents"].iloc[1])

str

In [39]:
def removeStopWords(text):
    doc=nlp(text)
    no_stop_words=[]
    for token in doc:
        if not token.is_stop and not token.is_punct:
            no_stop_words.append(token.text)
        
    return " ".join(no_stop_words)

In [40]:
df["contents_new"]=df["contents"].apply(removeStopWords)

In [41]:
df["contents"].iloc[3]

'21st Century Oncology LLC, has agreed to pay $19.75 million to the government to resolve allegations that it violated the False Claims Act by billing federal health care programs for laboratory tests that were not medically necessary, the Justice Department announced today.\xa0 21st Century is a nationwide provider of integrated cancer care services that is headquartered in Fort Myers, Florida.\xa0 “Today’s settlement demonstrates our unwavering commitment to protect the Medicare trust fund against unscrupulous providers,” said Principal Deputy Assistant Attorney General Benjamin C. Mizer, head of the Justice Department’s Civil Division.\xa0 “Providers who waste taxpayer dollars by billing for unnecessary services will face serious consequences.” The settlement announced today resolves allegations that 21st Century submitted claims to Medicare and Tricare for fluorescence in situ hybridization, or “FISH,” tests that were not medically necessary.\xa0 FISH tests are laboratory tests performed on urine that can detect genetic abnormalities associated with bladder cancer.\xa0 The government alleged that 21st Century submitted claims for unnecessary FISH tests that were ordered by four of its urologists, Dr. Meir Daller, Dr. Steven Paletsky, Dr. David Spellberg and Dr. Robert Scappa, all of whom practiced in the Fort Myers area.\xa0 The government also alleged that 21st Century encouraged these physicians to order unnecessary FISH tests by offering bonuses that were based in part on the number of tests referred to 21st Century’s laboratory.\xa0 Today’s settlement resolves the civil liability of 21st Century only.\xa0 “Charging the government for clearly unnecessary medical services squanders taxpayer dollars,” said U.S. Attorney A. Lee Bentley, III of the Middle District of Florida.\xa0 “Our office will continue to pursue health care providers who defraud the United States, thereby threatening the viability of government health care programs, such as Medicare.” “These tests were ordered to increase profits, not improve the healthcare of patients,” said Special Agent in Charge Shimon Richmond of the Department of Health and Human Services Office of Inspector General (HHS-OIG). “This kind of unvarnished fraud is an attack on Medicare by unscrupulous providers and the OIG and its federal partners will take whatever steps are necessary to stop them.” “This settlement demonstrates the commitment of the Defense Criminal Investigative Service (DCIS) and its law enforcement partners to protect the integrity of the U.S. military health care program (TRICARE) against fraudulent claims for medical services, said Special Agent in Charge John F. Khin of DCIS’s Southeast Field Office.” The settlement resolves allegations originally brought in a lawsuit filed by a whistleblower under the qui tam provisions of the False Claims Act, which allow private parties to bring suit on behalf of the government and to share in any recovery.\xa0 The whistleblower, a former 21st Century Oncology LLC medical assistant, will receive $3.2 million as her share of the recovery in this case. The investigation was handled by the Civil Division’s Commercial Litigation Branch and the Fort Myers Division of the U.S. Attorney’s Office of the Middle District of Florida with assistance from HHS-OIG, DCIS and the FBI.\xa0 This settlement illustrates the government’s emphasis on combating health care fraud and marks another achievement for the Health Care Fraud Prevention and Enforcement Action Team (HEAT) initiative, which was announced in May 2009 by the Attorney General and the Secretary of Health and Human Services.\xa0 The partnership between the two departments has focused efforts to reduce and prevent Medicare and Medicaid financial fraud through enhanced cooperation.\xa0 One of the most powerful tools in this effort is the False Claims Act.\xa0 Since January 2009, the Justice Department has recovered a total of more than $26.7 billion through False Claims Act cases, with more than $16.8 billion of that amount recovered in cases involving fraud against federal health care programs.\xa0\xa0 The lawsuit is captioned United States, State of Florida, ex rel. Mariela Barnes v. Dr. David Spellberg, 21st Century Oncology and Naples Urology Associates, Civil Action No. 2:13-cv-228-FtM-38DNF (M.D. Fla.).\xa0 The claims resolved by the settlement are allegations only, and there has been no determination of liability.\xa0'

In [42]:
df["contents_new"].iloc[3]

'21st Century Oncology LLC agreed pay $ 19.75 million government resolve allegations violated False Claims Act billing federal health care programs laboratory tests medically necessary Justice Department announced today \xa0  21st Century nationwide provider integrated cancer care services headquartered Fort Myers Florida \xa0  Today settlement demonstrates unwavering commitment protect Medicare trust fund unscrupulous providers said Principal Deputy Assistant Attorney General Benjamin C. Mizer head Justice Department Civil Division \xa0  Providers waste taxpayer dollars billing unnecessary services face consequences settlement announced today resolves allegations 21st Century submitted claims Medicare Tricare fluorescence situ hybridization FISH tests medically necessary \xa0  FISH tests laboratory tests performed urine detect genetic abnormalities associated bladder cancer \xa0  government alleged 21st Century submitted claims unnecessary FISH tests ordered urologists Dr. Meir Daller Dr. Steven Paletsky Dr. David Spellberg Dr. Robert Scappa practiced Fort Myers area \xa0  government alleged 21st Century encouraged physicians order unnecessary FISH tests offering bonuses based number tests referred 21st Century laboratory \xa0  Today settlement resolves civil liability 21st Century \xa0  Charging government clearly unnecessary medical services squanders taxpayer dollars said U.S. Attorney A. Lee Bentley III Middle District Florida \xa0  office continue pursue health care providers defraud United States threatening viability government health care programs Medicare tests ordered increase profits improve healthcare patients said Special Agent Charge Shimon Richmond Department Health Human Services Office Inspector General HHS OIG kind unvarnished fraud attack Medicare unscrupulous providers OIG federal partners steps necessary stop settlement demonstrates commitment Defense Criminal Investigative Service DCIS law enforcement partners protect integrity U.S. military health care program TRICARE fraudulent claims medical services said Special Agent Charge John F. Khin DCIS Southeast Field Office settlement resolves allegations originally brought lawsuit filed whistleblower qui tam provisions False Claims Act allow private parties bring suit behalf government share recovery \xa0  whistleblower 21st Century Oncology LLC medical assistant receive $ 3.2 million share recovery case investigation handled Civil Division Commercial Litigation Branch Fort Myers Division U.S. Attorney Office Middle District Florida assistance HHS OIG DCIS FBI \xa0  settlement illustrates government emphasis combating health care fraud marks achievement Health Care Fraud Prevention Enforcement Action Team HEAT initiative announced 2009 Attorney General Secretary Health Human Services \xa0  partnership departments focused efforts reduce prevent Medicare Medicaid financial fraud enhanced cooperation \xa0  powerful tools effort False Claims Act \xa0  January 2009 Justice Department recovered total $ 26.7 billion False Claims Act cases $ 16.8 billion recovered cases involving fraud federal health care programs \xa0\xa0  lawsuit captioned United States State Florida ex rel Mariela Barnes v. Dr. David Spellberg 21st Century Oncology Naples Urology Associates Civil Action 2:13 cv-228 FtM-38DNF M.D. Fla. \xa0  claims resolved settlement allegations determination liability \xa0'

In [44]:
df

,id,title,contents,date,topics,components,contents_new
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division],U.S. Department Justice U.S. Environmental Pro...
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division],131 count criminal indictment unsealed today B...
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U...",United States Attorney Office Middle District ...
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division],21st Century Oncology LLC agreed pay $ 19.75 m...
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]",21st Century Oncology Inc. certain subsidiarie...
...,...,...,...,...,...,...,...
316,15-1359,Alaska Plastic Surgeon Convicted of Wire Fraud...,Doctor Hid Millions in Secret Accounts in Pana...,2015-11-04T00:00:00-05:00,[Tax],[Tax Division],Doctor Hid Millions Secret Accounts Panama Ala...
318,16-396,Alaska Plastic Surgeon Sentenced to Prison for...,Defendant Concealed Bank Accounts in Panama an...,2016-04-04T00:00:00-04:00,[Tax],[Tax Division],Defendant Concealed Bank Accounts Panama Costa...
321,17-736,Alaskan Commercial Fishing Couple Charged with...,An Alaskan couple was charged in federal court...,2017-07-26T00:00:00-04:00,[Tax],"[Tax Division, USAO - Alaska]",Alaskan couple charged federal court Juneau Al...
322,18-717,Alaskan Husband And Wife Plead Guilty To Willf...,A husband and wife pleaded guilty yesterday to...,2018-06-01T00:00:00-04:00,[Tax],[Tax Division],husband wife pleaded guilty yesterday counts w...
324,16-1345,Alaskan Oncologist Indicted for Tax Evasion,"A resident of Big Lake, Alaska was indicted on...",2016-11-17T00:00:00-05:00,[Tax],[Tax Division],resident Big Lake Alaska indicted counts tax e...