## <font color="maroon"><h4 align="center">Handling Missing Data - replace method</font>

In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

**Replacing single value**

In [2]:
new_df=df.replace(-99999,np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

**Replacing list with single value**

In [4]:
new_df=df.replace([-99999,-88888],0)
new_df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017            0          7  Sunny
2  1/3/2017           28          0   Snow
3  1/4/2017            0          7      0
4  1/5/2017           32          0   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

**Replacing per column**

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          7 non-null      object
 1   temperature  7 non-null      int64
 2   windspeed    7 non-null      int64
 3   event        7 non-null      object
dtypes: int64(2), object(2)
memory usage: 352.0+ bytes

In [10]:
new_df=df.replace({
    "temperature":-99999,
    "windspeed":-99999,
    "event":"0"

},np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

**Replacing by using mapping**

In [13]:
new_df=df.replace({
    -99999:np.nan,
    "No Event":"Sunny"
})
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

**Regex**

In [15]:
# when windspeed is 6 mph, 7 mph etc. & temperature is 32 F, 28 F etc.
new_df=df.replace({
    "temperature":"[a-zA-z]",
    "windspeed":"[a-zA-z]"
},"",regex=True)
new_df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

**Replacing list with another list**

In [24]:
df = pd.DataFrame({
    'score': ['exceptional','average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [25]:
df["score"].value_counts()

score
exceptional    2
average        2
good           1
poor           1
Name: count, dtype: int64

In [26]:
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [27]:
new_df=df.replace(["exceptional","average","good","poor"],[4,3,2,1])
new_df

/var/folders/48/m5h2lpdd1nlc3bhw471fn9c00000gn/T/ipykernel_28145/2755451563.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_df=df.replace(["exceptional","average","good","poor"],[4,3,2,1])

   score  student
0      4      rob
1      3     maya
2      2  parthiv
3      1      tom
4      3   julian
5      4    erica