### Bag of words: Exercises


- In this Exercise, you are going to classify whether a given movie review is **positive or negative**.
- you are going to use Bag of words for pre-processing the text and apply different classification algorithms.
- Sklearn CountVectorizer has the inbuilt implementations for Bag of Words.

In [ ]:
#Import necessary libraries

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

### **About Data: IMDB Dataset**

Credits: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews?resource=download


- This data consists of two columns.
        - review
        - sentiment
- Reviews are the statements given by users after watching the movie.
- sentiment feature tells whether the given review is positive or negative.

In [2]:
#1. read the data provided in the same directory with name 'movies_sentiment_data.csv' and store it in df variable
df=pd.read_csv("movies_sentiment_data.csv")
df.head()

                                              review sentiment
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive
1  I enjoyed the movie and the story immensely! I...  positive
2  I had a hard time sitting through this. Every ...  negative
3  It's hard to imagine that anyone could find th...  negative
4  This is one military drama I like a lot! Tom B...  positive

In [4]:
#2. print the shape of the data
df.shape

(19000, 2)

In [5]:

#3. print top 5 datapoints
df.head(5)

                                              review sentiment
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive
1  I enjoyed the movie and the story immensely! I...  positive
2  I had a hard time sitting through this. Every ...  negative
3  It's hard to imagine that anyone could find th...  negative
4  This is one military drama I like a lot! Tom B...  positive

In [8]:
df["sentiment"].value_counts()

sentiment
positive    9500
negative    9500
Name: count, dtype: int64

In [12]:
#creating a new column "Category" which represent 1 if the sentiment is positive or 0 if it is negative
def change_to_integer(x):
    if x=="positive":
        return 1
    else:
        return 0
df["Category"]=df["sentiment"].apply(change_to_integer)
df.head()

                                              review sentiment  Category
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive         1
1  I enjoyed the movie and the story immensely! I...  positive         1
2  I had a hard time sitting through this. Every ...  negative         0
3  It's hard to imagine that anyone could find th...  negative         0
4  This is one military drama I like a lot! Tom B...  positive         1

In [14]:
#check the distribution of 'Category' and see whether the Target labels are balanced or not.

df["Category"].value_counts()

Category
1    9500
0    9500
Name: count, dtype: int64

In [15]:
y=df["Category"]
X=df["review"]

In [16]:
#Do the 'train-test' splitting with test size of 20%

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [17]:
len(X_train)

15200

In [18]:
len(X_test)

3800

In [20]:
len(X_test)/len(X_train)

0.25

**Exercise-1**

1. using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative.

**Note:**
- use CountVectorizer for pre-processing the text.

- use **Random Forest** as the classifier with estimators as 50 and criterion as entropy.
- print the classification report.

**References**:

- https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

- https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

In [26]:
#1. create a pipeline object
from sklearn.pipeline import Pipeline

steps = [
    ('preprocessing', CountVectorizer()),
    ('classifier', RandomForestClassifier(n_estimators=50))
]
pipe = Pipeline(steps)

In [27]:
#2. fit with X_train and y_train
pipe.fit(X_train, y_train)

Pipeline(steps=[('preprocessing', CountVectorizer()),
                ('classifier', RandomForestClassifier(n_estimators=50))])

In [28]:
#3. get the predictions for X_test and store it in y_pred
y_pred=pipe.predict(X_test)

In [30]:
#4. print the classfication report
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.85      0.83      1864
           1       0.85      0.81      0.83      1936

    accuracy                           0.83      3800
   macro avg       0.83      0.83      0.83      3800
weighted avg       0.83      0.83      0.83      3800

**Exercise-2**

1. using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative..

**Note:**
- use CountVectorizer for pre-processing the text.
- use **KNN** as the classifier with n_neighbors of 10 and metric as 'euclidean'.
- print the classification report.

**References**:

- https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
- https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

In [33]:
#1. create a pipeline object
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
# Define the steps as a list of (name, estimator) tuples
steps = [
    ('vectorizer', CountVectorizer()),
    ('classifier', KNeighborsClassifier(n_neighbors=10,metric="euclidean"))
]
pipe=Pipeline(steps)

In [34]:
#2. fit with X_train and y_train
pipe.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('classifier',
                 KNeighborsClassifier(metric='euclidean', n_neighbors=10))])

In [35]:
#3. get the predictions for X_test and store it in y_pred
y_pred=pipe.predict(X_test)

In [36]:



#4. print the classfication report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.64      0.64      0.64      1864
           1       0.65      0.65      0.65      1936

    accuracy                           0.65      3800
   macro avg       0.65      0.65      0.65      3800
weighted avg       0.65      0.65      0.65      3800

**Exercise-3**

1. using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative..

**Note:**
- use CountVectorizer for pre-processing the text.
- use **Multinomial Naive Bayes** as the classifier.
- print the classification report.

**References**:

- https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
- https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html

In [39]:
from sklearn import pipeline
from sklearn.naive_bayes import MultinomialNB
#1. create a pipeline object
steps=[
    ("vectorizer",CountVectorizer()),
    ("classifier",MultinomialNB())
]

pipe=Pipeline(steps)

In [41]:

#2. fit with X_train and y_train
pipe.fit(X_train,y_train)


#3. get the predictions for X_test and store it in y_pred

y_pred=pipe.predict(X_test)

#4. print the classfication report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.88      0.85      1864
           1       0.87      0.81      0.84      1936

    accuracy                           0.84      3800
   macro avg       0.85      0.84      0.84      3800
weighted avg       0.85      0.84      0.84      3800

### Can you write some observations of why model like KNN fails to produce good results unlike RandomForest and MultinomialNB?

- As Machine learning algorithms does not work on Text data directly, we need to convert them into numeric vector and feed that into models while training.
- In this process, we convert text into a very **high dimensional numeric vector** using the technique of Bag of words.
- Model like K-Nearest Neighbours(KNN) doesn't work well with high dimensional data because with large number of dimensions, it becomes difficult for the algorithm to calculate distance in each dimension. In higher dimensional space, the cost to calculate distance becomes expensive and hence impacts the performance of model.
- The easy calculation of probabilities for the words in corpus(Bag of words) and storing them in contigency table is the major reason for the Multinomial NaiveBayes to be a text classification friendly algorithm.
- As Random Forest uses Bootstrapping(Row and column Sampling) with many decision tree and overcomes the high variance and overfitting of high dimensional data and also uses feature importance of words for better classifing the categories.
- Machine Learning is like trial and error scientific method, where we keep trying all the possible algorithms we have and select the one which give good results and satisfy the requirements like latency, interpretability etc.

Refer these resources to get good idea:
- https://stackabuse.com/k-nearest-neighbors-algorithm-in-python-and-scikit-learn/
- https://analyticsindiamag.com/naive-bayes-why-is-it-favoured-for-text-related-tasks/