In [1]:
import pandas as pd

df=pd.read_csv("fb.csv",parse_dates=["Date"],index_col="Date")
df

/var/folders/48/m5h2lpdd1nlc3bhw471fn9c00000gn/T/ipykernel_7287/1415289420.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df=pd.read_csv("fb.csv",parse_dates=["Date"],index_col="Date")

             Price
Date
2017-08-15  171.00
2017-08-16  170.00
2017-08-17  166.91
2017-08-18  167.41
2017-08-21  167.78
2017-08-22  169.64
2017-08-23  168.71
2017-08-24  167.74
2017-08-25  166.32
2017-08-28  167.24

<img src="shift_image.png" />

<h2 style="color:purple">Shift</h2>

In [2]:
df.shift(1)

             Price
Date
2017-08-15     NaN
2017-08-16  171.00
2017-08-17  170.00
2017-08-18  166.91
2017-08-21  167.41
2017-08-22  167.78
2017-08-23  169.64
2017-08-24  168.71
2017-08-25  167.74
2017-08-28  166.32

In [3]:
df.shift(-1)

             Price
Date
2017-08-15  170.00
2017-08-16  166.91
2017-08-17  167.41
2017-08-18  167.78
2017-08-21  169.64
2017-08-22  168.71
2017-08-23  167.74
2017-08-24  166.32
2017-08-25  167.24
2017-08-28     NaN

In [4]:
df["Prev_Price"]=df["Price"].shift(1)
df

             Price  Prev_Price
Date
2017-08-15  171.00         NaN
2017-08-16  170.00      171.00
2017-08-17  166.91      170.00
2017-08-18  167.41      166.91
2017-08-21  167.78      167.41
2017-08-22  169.64      167.78
2017-08-23  168.71      169.64
2017-08-24  167.74      168.71
2017-08-25  166.32      167.74
2017-08-28  167.24      166.32

In [5]:
df["Price_Change"]=df["Price"]-df["Prev_Price"]
df

             Price  Prev_Price  Price_Change
Date
2017-08-15  171.00         NaN           NaN
2017-08-16  170.00      171.00         -1.00
2017-08-17  166.91      170.00         -3.09
2017-08-18  167.41      166.91          0.50
2017-08-21  167.78      167.41          0.37
2017-08-22  169.64      167.78          1.86
2017-08-23  168.71      169.64         -0.93
2017-08-24  167.74      168.71         -0.97
2017-08-25  166.32      167.74         -1.42
2017-08-28  167.24      166.32          0.92

In [7]:
df["5days"]=df["Price"].shift(5)
df

             Price  Prev_Price  Price_Change   5days
Date
2017-08-15  171.00         NaN           NaN     NaN
2017-08-16  170.00      171.00         -1.00     NaN
2017-08-17  166.91      170.00         -3.09     NaN
2017-08-18  167.41      166.91          0.50     NaN
2017-08-21  167.78      167.41          0.37     NaN
2017-08-22  169.64      167.78          1.86  171.00
2017-08-23  168.71      169.64         -0.93  170.00
2017-08-24  167.74      168.71         -0.97  166.91
2017-08-25  166.32      167.74         -1.42  167.41
2017-08-28  167.24      166.32          0.92  167.78

In [8]:
df["5_day_%_return"]=((df["Price"]-df["5days"])/df["5days"])*100
df

             Price  Prev_Price  Price_Change   5days  5_day_%_return
Date
2017-08-15  171.00         NaN           NaN     NaN             NaN
2017-08-16  170.00      171.00         -1.00     NaN             NaN
2017-08-17  166.91      170.00         -3.09     NaN             NaN
2017-08-18  167.41      166.91          0.50     NaN             NaN
2017-08-21  167.78      167.41          0.37     NaN             NaN
2017-08-22  169.64      167.78          1.86  171.00       -0.795322
2017-08-23  168.71      169.64         -0.93  170.00       -0.758824
2017-08-24  167.74      168.71         -0.97  166.91        0.497274
2017-08-25  166.32      167.74         -1.42  167.41       -0.651096
2017-08-28  167.24      166.32          0.92  167.78       -0.321850

In [9]:
df=df[["Price"]]
df

             Price
Date
2017-08-15  171.00
2017-08-16  170.00
2017-08-17  166.91
2017-08-18  167.41
2017-08-21  167.78
2017-08-22  169.64
2017-08-23  168.71
2017-08-24  167.74
2017-08-25  166.32
2017-08-28  167.24

<h2 style="color:purple">tshift</h2>

In [10]:
df.index

DatetimeIndex(['2017-08-15', '2017-08-16', '2017-08-17', '2017-08-18',
               '2017-08-21', '2017-08-22', '2017-08-23', '2017-08-24',
               '2017-08-25', '2017-08-28'],
              dtype='datetime64[ns]', name='Date', freq=None)

In [11]:
df.index=pd.date_range(start="2017-08-15",periods=10,freq="B")
df

             Price
2017-08-15  171.00
2017-08-16  170.00
2017-08-17  166.91
2017-08-18  167.41
2017-08-21  167.78
2017-08-22  169.64
2017-08-23  168.71
2017-08-24  167.74
2017-08-25  166.32
2017-08-28  167.24

In [12]:
df.index

DatetimeIndex(['2017-08-15', '2017-08-16', '2017-08-17', '2017-08-18',
               '2017-08-21', '2017-08-22', '2017-08-23', '2017-08-24',
               '2017-08-25', '2017-08-28'],
              dtype='datetime64[ns]', freq='B')

In [16]:
df.shift(1,freq="B")

             Price
2017-08-16  171.00
2017-08-17  170.00
2017-08-18  166.91
2017-08-21  167.41
2017-08-22  167.78
2017-08-23  169.64
2017-08-24  168.71
2017-08-25  167.74
2017-08-28  166.32
2017-08-29  167.24