## <font color="purple"><h4 align="center">Read/Write CSV and Excel Files in Pandas</font>

### <font color="blue">Read CSV</color>

In [4]:
import pandas as pd
df=pd.read_csv("stock_data.csv")
df

  stocksdata              1        2      3              4
0    tickers            eps  revenue  price         people
1      GOOGL          27.82       87    845     larry page
2        WMT           4.61      484     65           n.a.
3       MSFT             -1       85     64     bill gates
4       RIL   not available       50   1023  mukesh ambani
5       TATA            5.6       -1   n.a.     ratan tata

In [5]:
df=pd.read_csv("stock_data.csv",skiprows=1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [10]:
df=pd.read_csv("stock_data.csv",header=1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [12]:
df=pd.read_csv("stock_data.csv",header=None)
df

            0              1        2      3              4
0  stocksdata              1        2      3              4
1     tickers            eps  revenue  price         people
2       GOOGL          27.82       87    845     larry page
3         WMT           4.61      484     65           n.a.
4        MSFT             -1       85     64     bill gates
5        RIL   not available       50   1023  mukesh ambani
6        TATA            5.6       -1   n.a.     ratan tata

In [13]:
df.columns

Index([0, 1, 2, 3, 4], dtype='int64')

In [14]:
df=pd.read_csv("stock_data.csv",header=None,names=["name1","name2","name3","name4","name5"])
df

        name1          name2    name3  name4          name5
0  stocksdata              1        2      3              4
1     tickers            eps  revenue  price         people
2       GOOGL          27.82       87    845     larry page
3         WMT           4.61      484     65           n.a.
4        MSFT             -1       85     64     bill gates
5        RIL   not available       50   1023  mukesh ambani
6        TATA            5.6       -1   n.a.     ratan tata

In [15]:
df = pd.read_csv("stock_data.csv",  nrows=2)
df

  stocksdata      1        2      3           4
0    tickers    eps  revenue  price      people
1      GOOGL  27.82       87    845  larry page

In [16]:
df=pd.read_csv("stock_data.csv",na_values=["n.a.","not available"])
df

  stocksdata      1        2      3              4
0    tickers    eps  revenue  price         people
1      GOOGL  27.82       87    845     larry page
2        WMT   4.61      484     65            NaN
3       MSFT     -1       85     64     bill gates
4       RIL     NaN       50   1023  mukesh ambani
5       TATA    5.6       -1    NaN     ratan tata

In [18]:
df=pd.read_csv("stock_data.csv",skiprows=1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [20]:
for column in df.columns:
    print(f"{column}:")
    print(df[column].unique())

tickers:
['GOOGL' 'WMT' 'MSFT' 'RIL ' 'TATA']
eps:
['27.82' '4.61' '-1' 'not available' '5.6']
revenue:
[ 87 484  85  50  -1]
price:
['845' '65' '64' '1023' 'n.a.']
people:
['larry page' 'n.a.' 'bill gates' 'mukesh ambani' 'ratan tata']

In [21]:
df=pd.read_csv("stock_data.csv",skiprows=1,na_values={
    "eps":["not available","n.a"],
    "revenue":["-1"],
    "people":["n.a."]
})

In [22]:
df

  tickers    eps  revenue price         people
0   GOOGL  27.82     87.0   845     larry page
1     WMT   4.61    484.0    65            NaN
2    MSFT  -1.00     85.0    64     bill gates
3    RIL     NaN     50.0  1023  mukesh ambani
4    TATA   5.60      NaN  n.a.     ratan tata

### <font color="blue">Write to CSV</color>

In [23]:
df.to_csv("new_cleaned.csv")

In [24]:
df.to_csv("new_cleaned.csv",index=False)

In [24]:
df.columns

Index(['tickers', 'eps', 'revenue', 'price', 'people'], dtype='object')

In [25]:
df.to_csv("new1.csv",header=False)

In [26]:
df.to_csv("new2.csv",columns=["tickers","eps"],index=False)

### <font color="blue">Read Excel</color>

In [29]:
df=pd.read_excel("stock_data.xlsx")

In [31]:
df=pd.read_excel("stock_data.xlsx",sheet_name="Sheet1")

In [32]:
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [40]:
from math import nan


def convert_people_cell(cell):
    if cell=="n.a.":
        return nan  # return Kristal
    return cell


def convert_eps_cell(cell):
    if cell== "not available":
        return None
    return cell


df=pd.read_excel("stock_data.xlsx",sheet_name="Sheet1",converters={
    "people":convert_people_cell,
    "eps":convert_eps_cell
})

In [41]:
df

  tickers    eps  revenue price         people
0   GOOGL  27.82       87   845     larry page
1     WMT   4.61      484    65            NaN
2    MSFT  -1.00       85    64     bill gates
3    RIL     NaN       50  1023  mukesh ambani
4    TATA   5.60       -1  n.a.     ratan tata

### <font color="blue">Write to Excel</color>

In [43]:
df.to_excel("new1.xlsx",sheet_name="KristalSheet",index=False)

**Write two dataframes to two separate sheets in excel**

In [45]:
df_stocks = pd.DataFrame({
    'tickers': ['GOOGL', 'WMT', 'MSFT'],
    'price': [845, 65, 64 ],
    'pe': [30.37, 14.26, 30.97],
    'eps': [27.82, 4.61, 2.12]
})

df_weather =  pd.DataFrame({
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'event': ['Rain', 'Sunny', 'Snow']
})

In [46]:
with pd.ExcelWriter("two_dataframe.xlsx") as writer:
    df_stocks.to_excel(writer,sheet_name="Sheet1")
    df_weather.to_excel(writer,sheet_name="Sheet2")