<h2 style='color:blue' align="center">Decision Tree Classification</h2>

**Exercise: Build decision tree model to predict survival based on certain parameters**

<img src="titanic.jpg" height=200 width=400/>

CSV file is available to download at https://github.com/codebasics/py/blob/master/ML/9_decision_tree/Exercise/titanic.csv

##### In this file using following columns build a model to predict if person would survive or not,

1. Pclass
1. Sex
1. Age
1. Fare

##### Calculate score of your model

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("titanic.csv")

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
df.drop(["PassengerId","Name","Parch","Ticket","Cabin","Embarked"],axis="columns",inplace=True)

In [9]:
df

     Survived  Pclass     Sex   Age  SibSp     Fare
0           0       3    male  22.0      1   7.2500
1           1       1  female  38.0      1  71.2833
2           1       3  female  26.0      0   7.9250
3           1       1  female  35.0      1  53.1000
4           0       3    male  35.0      0   8.0500
..        ...     ...     ...   ...    ...      ...
886         0       2    male  27.0      0  13.0000
887         1       1  female  19.0      0  30.0000
888         0       3  female   NaN      1  23.4500
889         1       1    male  26.0      0  30.0000
890         0       3    male  32.0      0   7.7500

[891 rows x 6 columns]

In [10]:
inputs=df.drop(["Survived"],axis="columns")
inputs

     Pclass     Sex   Age  SibSp     Fare
0         3    male  22.0      1   7.2500
1         1  female  38.0      1  71.2833
2         3  female  26.0      0   7.9250
3         1  female  35.0      1  53.1000
4         3    male  35.0      0   8.0500
..      ...     ...   ...    ...      ...
886       2    male  27.0      0  13.0000
887       1  female  19.0      0  30.0000
888       3  female   NaN      1  23.4500
889       1    male  26.0      0  30.0000
890       3    male  32.0      0   7.7500

[891 rows x 5 columns]

In [11]:
inputs.Sex=inputs.Sex.map({"male":1,"female":2})

In [12]:
inputs

     Pclass  Sex   Age  SibSp     Fare
0         3    1  22.0      1   7.2500
1         1    2  38.0      1  71.2833
2         3    2  26.0      0   7.9250
3         1    2  35.0      1  53.1000
4         3    1  35.0      0   8.0500
..      ...  ...   ...    ...      ...
886       2    1  27.0      0  13.0000
887       1    2  19.0      0  30.0000
888       3    2   NaN      1  23.4500
889       1    1  26.0      0  30.0000
890       3    1  32.0      0   7.7500

[891 rows x 5 columns]

# but the good way is to use LabelEncoder

In [14]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
inputs["Sex"]=le.fit_transform(inputs["Sex"])
inputs

     Pclass  Sex   Age  SibSp     Fare
0         3    0  22.0      1   7.2500
1         1    1  38.0      1  71.2833
2         3    1  26.0      0   7.9250
3         1    1  35.0      1  53.1000
4         3    0  35.0      0   8.0500
..      ...  ...   ...    ...      ...
886       2    0  27.0      0  13.0000
887       1    1  19.0      0  30.0000
888       3    1   NaN      1  23.4500
889       1    0  26.0      0  30.0000
890       3    0  32.0      0   7.7500

[891 rows x 5 columns]

In [15]:
inputs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Pclass  891 non-null    int64
 1   Sex     891 non-null    int64
 2   Age     714 non-null    float64
 3   SibSp   891 non-null    int64
 4   Fare    891 non-null    float64
dtypes: float64(2), int64(3)
memory usage: 34.9 KB

# so age has some null values

In [16]:
age_mean=inputs["Age"].mean()

In [17]:
inputs["Age"]=inputs["Age"].fillna(inputs["Age"].mean())

In [18]:
inputs

     Pclass  Sex        Age  SibSp     Fare
0         3    0  22.000000      1   7.2500
1         1    1  38.000000      1  71.2833
2         3    1  26.000000      0   7.9250
3         1    1  35.000000      1  53.1000
4         3    0  35.000000      0   8.0500
..      ...  ...        ...    ...      ...
886       2    0  27.000000      0  13.0000
887       1    1  19.000000      0  30.0000
888       3    1  29.699118      1  23.4500
889       1    0  26.000000      0  30.0000
890       3    0  32.000000      0   7.7500

[891 rows x 5 columns]

In [19]:
inputs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Pclass  891 non-null    int64
 1   Sex     891 non-null    int64
 2   Age     891 non-null    float64
 3   SibSp   891 non-null    int64
 4   Fare    891 non-null    float64
dtypes: float64(2), int64(3)
memory usage: 34.9 KB

In [20]:
target=df["Survived"]

In [21]:
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(inputs,target,test_size=0.2,random_state=10)

In [23]:
from sklearn import tree

model=tree.DecisionTreeClassifier()

In [24]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [25]:
model.score(X_test,y_test)

0.7877094972067039

In [26]:
model.predict(X_test)

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0])

In [27]:
y_test

590    0
131    0
628    0
195    1
230    1
      ..
456    0
191    0
603    0
94     0
766    0
Name: Survived, Length: 179, dtype: int64