### **Bag of n_grams: Exercise**

- Fake news refers to misinformation or disinformation in the country which is spread through word of mouth and more recently through digital communication such as What's app messages, social media posts, etc.

- Fake news spreads faster than Real news and creates problems and fear among groups and in society.

- We are going to address these problems using classical NLP techniques and going to classify whether a given message/ text is **Real or Fake Message**.

- You will use a Bag of n-grams to pre-process the text and apply different classification algorithms.

- Sklearn CountVectorizer has the inbuilt implementations for Bag of Words.

### **About Data: Fake News Detection**

Credits: https://www.kaggle.com/datasets/clmentbisaillon/fake-and-real-news-dataset


- This data consists of two columns.
        - Text
        - label
- Text is the statements or messages regarding a particular event/situation.

- label feature tells whether the given Text is Fake or Real.

- As there are only 2 classes, this problem comes under the **Binary Classification.**

In [4]:
#import pandas library

#read the dataset with name "Fake_Real_Data.csv" and store it in a variable df
import pandas as pd
df=pd.read_csv("Fake_Real_Data.csv")

In [2]:

#print the shape of dataframe
df.shape

(9900, 2)

In [3]:
#print top 5 rows
df.head()

                                                Text label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1  U.S. conservative leader optimistic of common ...  Real
2  Trump proposes U.S. tax overhaul, stirs concer...  Real
3   Court Forces Ohio To Allow Millions Of Illega...  Fake
4  Democrats say Trump agrees to work on immigrat...  Real

In [6]:
#check the distribution of labels 
df["label"].value_counts()

label
Fake    5000
Real    4900
Name: count, dtype: int64

In [7]:
#Add the new column "label_num" which gives a unique number to each of these labels 
mappings={"Fake":0,"Real":1}
df["label_num"]=df["label"].map(mappings)
#check the results with top 5 rows
df.head()

                                                Text label  label_num
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake          0
1  U.S. conservative leader optimistic of common ...  Real          1
2  Trump proposes U.S. tax overhaul, stirs concer...  Real          1
3   Court Forces Ohio To Allow Millions Of Illega...  Fake          0
4  Democrats say Trump agrees to work on immigrat...  Real          1

### **Modelling without Pre-processing Text data**

In [9]:
#import train-test-split from sklearn 
from sklearn.model_selection import train_test_split

#Do the 'train-test' splitting with test size of 20% with random state of 2022 and stratify sampling too
X_train,X_test,y_train,y_test=train_test_split(df["Text"],df["label_num"],test_size=0.2,random_state=2025,stratify=df["label_num"])

In [11]:
#print the shapes of X_train and X_test
print(X_train.shape)
X_test.shape

(7920,)

(1980,)

**Attempt 1** :

1. using sklearn pipeline module create a classification pipeline to classify the Data.

**Note:**
- using CountVectorizer with unigram, bigram, and trigrams.
- use KNN as the classifier with n_neighbors of 10 and metric as 'euclidean' distance.
- print the classification report.

In [12]:
#1. create a pipeline object
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import KNeighborsClassifier
steps=[
    ("vectorizer",CountVectorizer()),
    ("classifier",KNeighborsClassifier(n_neighbors=10,metric="euclidean"))
]
model=Pipeline(steps)

In [13]:

#2. fit with X_train and y_train
model.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('classifier',
                 KNeighborsClassifier(metric='euclidean', n_neighbors=10))])

In [14]:
#3. get the predictions for X_test and store it in y_pred
y_pred=model.predict(X_test)

In [15]:

#4. print the classfication report
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.92      0.94      1000
           1       0.92      0.96      0.94       980

    accuracy                           0.94      1980
   macro avg       0.94      0.94      0.94      1980
weighted avg       0.94      0.94      0.94      1980

**Attempt 2** :

1. using the sklearn pipeline module create a classification pipeline to classify the Data.

**Note:**
- using CountVectorizer with unigram, bigram, and trigrams.
- use **KNN** as the classifier with n_neighbors of 10 and metric as 'cosine' distance.
- print the classification report.

In [ ]:
#1. create a pipeline object
from sklearn.pipeline import Pipeline
steps=[
    ("vectorizer",CountVectorizer(ngram_range=(2,2))),
    ("classifier",KNeighborsClassifier(n_neighbors=10,metric="euclidean"))
]
model=Pipeline(steps)


#2. fit with X_train and y_train
model.fit(X_train,y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred=model.predict(X_test)

In [17]:
#4. print the classfication report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1000
           1       0.49      1.00      0.66       980

    accuracy                           0.49      1980
   macro avg       0.25      0.50      0.33      1980
weighted avg       0.24      0.49      0.33      1980

/Users/kristalshrestha/Documents/Code/LLM_Scratch/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/kristalshrestha/Documents/Code/LLM_Scratch/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/kristalshrestha/Documents/Code/LLM_Scratch/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


**Attempt 3** :

1. using the sklearn pipeline module create a classification pipeline to classify the Data.

**Note:**
- using CountVectorizer with only trigrams.
- use **RandomForest** as the classifier.
- print the classification report.

In [20]:
#1. create a pipeline object
from sklearn.pipeline import Pipeline
steps=[
    ("vectorizer",CountVectorizer(ngram_range=(3,3))),
    ("classifier",KNeighborsClassifier(n_neighbors=10,metric="euclidean"))
]
model=Pipeline(steps)


#2. fit with X_train and y_train
model.fit(X_train,y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred=model.predict(X_test)

In [21]:
#4. print the classfication report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1000
           1       0.49      1.00      0.66       980

    accuracy                           0.49      1980
   macro avg       0.25      0.50      0.33      1980
weighted avg       0.24      0.49      0.33      1980

/Users/kristalshrestha/Documents/Code/LLM_Scratch/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/kristalshrestha/Documents/Code/LLM_Scratch/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/kristalshrestha/Documents/Code/LLM_Scratch/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


**Attempt 4** :

1. using the sklearn pipeline module create a classification pipeline to classify the Data.

**Note:**
- using CountVectorizer with both unigram and bigrams.
- use **Multinomial Naive Bayes** as the classifier with an alpha value of 0.75.
- print the classification report.

In [22]:
#1. create a pipeline object
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
steps=[
    ("vectorizer",CountVectorizer(ngram_range=(1,2))),
    ("classifier",MultinomialNB(alpha=0.75))
]
model=Pipeline(steps)


#2. fit with X_train and y_train
model.fit(X_train,y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred=model.predict(X_test)

In [23]:
#4. print the classfication report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98      1000
           1       0.98      0.99      0.98       980

    accuracy                           0.98      1980
   macro avg       0.98      0.98      0.98      1980
weighted avg       0.98      0.98      0.98      1980

<h3>Use text pre-processing to remove stop words, punctuations and apply lemmatization </h3>

In [24]:
#use this utility function to get the preprocessed text data

import spacy

# load english language model and create nlp object from it
nlp = spacy.load("en_core_web_sm") 

def preprocess(text):
    # remove stop words and lemmatize the text
    doc = nlp(text)
    filtered_tokens = []
    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_tokens.append(token.lemma_)
    
    return " ".join(filtered_tokens)

In [25]:
df.head()

                                                Text label  label_num
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake          0
1  U.S. conservative leader optimistic of common ...  Real          1
2  Trump proposes U.S. tax overhaul, stirs concer...  Real          1
3   Court Forces Ohio To Allow Millions Of Illega...  Fake          0
4  Democrats say Trump agrees to work on immigrat...  Real          1

In [ ]:
# create a new column "preprocessed_txt" and use the utility function above to get the clean data
# this will take some time, please be patient
df["preprocessed_txt"]=df["Text"].apply(preprocess)

In [ ]:
#print the top 5 rows
df.head()

**Build a model with pre processed text**

In [ ]:
#Do the 'train-test' splitting with test size of 20% with random state of 2022 and stratify sampling too
#Note: Make sure to use only the "preprocessed_txt" column for splitting
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2025,stratify=df["preprocessed_txt"])

**Let's check the scores with our best model till now**
- Random Forest

**Attempt1** :

1. using the sklearn pipeline module create a classification pipeline to classify the Data.

**Note:**
- using CountVectorizer with only trigrams.
- use **RandomForest** as the classifier.
- print the classification report.

In [12]:
#1. create a pipeline object



#2. fit with X_train and y_train



#3. get the predictions for X_test and store it in y_pred



#4. print the classfication report

**Attempt2** :

1. using the sklearn pipeline module create a classification pipeline to classify the Data.

**Note:**
- using CountVectorizer with unigram, Bigram, and trigrams.
- use **RandomForest** as the classifier.
- print the classification report.

In [13]:
#1. create a pipeline object




#2. fit with X_train and y_train



#3. get the predictions for X_test and store it in y_pred



#4. print the classfication report

In [14]:
#finally print the confusion matrix for the best model

## **Please write down Final Observations**